version: 2
jobs:
  build:
    working_directory: ~/eram-folder
    shell: /bin/bash --login
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: v1-dep-{{ .Branch }}-
      - save_cache:
          key:  v1-dep-{{ .Branch }}-{{ epoch }}
          paths:
            - vendor/bundle
            - ~/virtualenvs
            - ~/.m2
            - ~/.ivy2
            - ~/.bundle
            - ~/.go_workspace
            - ~/.gradle
            - ~/.cache/bower
            # These cache paths were specified in the 1.0 config
            - ~/.android
            - ~/android
      - run:
          name: chmod permissions
          command: sudo chmod +x ./gradlew
      - run: ./gradlew build
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - run:
          name: Creating Dummy Artifacts
          command: |
            sudo mkdir -m 0755  -p /eram-folder/artifacts;
            echo "my artifact files in a dir" > /eram-folder/artifacts/a.txt;

      - store_artifacts:
          path: /eram-folder/artifacts
          destination: artifact-file
      - store_test_results:
          path: /eram-folder/eram-common-test-results