version: 2
jobs:
  build:
    working_directory: ~/eram-folder
    shell: /bin/bash --login
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      TEST_REPORTS: /tmp/eram-common-test-results
    steps:
      - checkout
      - restore_cache:
          key: v1-dep-{{ .Branch }}-
      - save_cache:
          key:  v1-dep-{{ .Branch }}-{{ epoch }}
          paths:
            - vendor/bundle
            - ~/virtualenvs
            - ~/.m2
            - ~/.ivy2
            - ~/.bundle
            - ~/.go_workspace
            - ~/.gradle
            - ~/.cache/bower
            # These cache paths were specified in the 1.0 config
            - ~/.android
            - ~/android
      - run:
          name: chmod permissions
          command: sudo chmod +x ./gradlew
      - run: ./gradlew build
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - run:
          environment:
            SSH_TARGET: "localhost"
            TEST_ENV: "linux"
          command: |
            set -xu
            mkdir -p ${TEST_REPORTS}
      - run: |
          set -xu
          mkdir -p /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
          destination: build
      - store_test_results:
          path: /tmp/eram-common-test-results