version: 2
jobs:
  build:
    working_directory: ~/eram-folder
    shell: /bin/bash --login
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "eram-cm/build.gradle" }}
      - save_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "eram-cm/build.gradle" }}
          paths:
            - ~/.gradle
  test:
    working_directory: ~/eram-folder
    shell: /bin/bash --login
    docker:
        - image: circleci/android:api-28-alpha
    environment:
        JVM_OPTS: -Xmx3200m
        TEST_REPORTS: eram-cm/build/test-results
    steps:
      - checkout
      - run:
          name: chmod permissions
          command: sudo chmod +x ./gradlew
      - run: ./gradlew build
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: eram-cm/build/reports
          destination: reports
      - store_test_results:
          path: eram-cm/build/test-results

workflows:
  version: 2
  build_and_test:
      jobs:
        - build
        - test:
            - requires:
                build